import type { ComponentProps } from "react";
import type { Ionicons } from "@expo/vector-icons";

export type IoniconsName = ComponentProps<typeof Ionicons>["name"];

export interface CategoryDef {
  id: string;
  name: IoniconsName;
  label: string;
  builtIn: boolean;
}

export const BUILTIN_CATEGORIES: CategoryDef[] = [
  { id: "builtin:body", name: "body-outline", label: "Body", builtIn: true },
  { id: "builtin:fitness", name: "barbell-outline", label: "Fitness", builtIn: true },
  { id: "builtin:plants", name: "flower-outline", label: "Plants", builtIn: true },
  { id: "builtin:home", name: "home-outline", label: "Home", builtIn: true },
  { id: "builtin:build", name: "hammer-outline", label: "Build", builtIn: true },
  { id: "builtin:health", name: "heart-outline", label: "Health", builtIn: true },
  { id: "builtin:nature", name: "leaf-outline", label: "Nature", builtIn: true },
  { id: "builtin:sport", name: "bicycle-outline", label: "Sport", builtIn: true },
  { id: "builtin:diet", name: "restaurant-outline", label: "Diet", builtIn: true },
  { id: "builtin:medical", name: "medkit-outline", label: "Medical", builtIn: true },
  { id: "builtin:photo", name: "camera-outline", label: "Photo", builtIn: true },
  { id: "builtin:study", name: "book-outline", label: "Study", builtIn: true },
  { id: "builtin:music", name: "musical-notes-outline", label: "Music", builtIn: true },
  { id: "builtin:walk", name: "walk-outline", label: "Walk", builtIn: true },
  { id: "builtin:metrics", name: "analytics-outline", label: "Metrics", builtIn: true },
  { id: "builtin:art", name: "brush-outline", label: "Art", builtIn: true },
];

/** Curated icon set offered when creating a custom category. */
export const ICON_PICKER_OPTIONS: IoniconsName[] = [
  "body-outline",
  "barbell-outline",
  "flower-outline",
  "home-outline",
  "hammer-outline",
  "heart-outline",
  "leaf-outline",
  "bicycle-outline",
  "restaurant-outline",
  "medkit-outline",
  "camera-outline",
  "book-outline",
  "musical-notes-outline",
  "walk-outline",
  "analytics-outline",
  "brush-outline",
  "airplane-outline",
  "boat-outline",
  "car-outline",
  "bus-outline",
  "train-outline",
  "rocket-outline",
  "earth-outline",
  "compass-outline",
  "map-outline",
  "globe-outline",
  "paw-outline",
  "fish-outline",
  "egg-outline",
  "pizza-outline",
  "cafe-outline",
  "wine-outline",
  "beer-outline",
  "ice-cream-outline",
  "fast-food-outline",
  "nutrition-outline",
  "fitness-outline",
  "footsteps-outline",
  "trophy-outline",
  "ribbon-outline",
  "medal-outline",
  "star-outline",
  "diamond-outline",
  "flame-outline",
  "sparkles-outline",
  "color-palette-outline",
  "construct-outline",
  "build-outline",
  "briefcase-outline",
  "school-outline",
  "library-outline",
  "newspaper-outline",
  "mic-outline",
  "headset-outline",
  "videocam-outline",
  "film-outline",
  "game-controller-outline",
  "tv-outline",
  "phone-portrait-outline",
  "laptop-outline",
  "code-slash-outline",
  "cloud-outline",
  "sunny-outline",
  "moon-outline",
  "snow-outline",
  "rainy-outline",
  "thunderstorm-outline",
  "umbrella-outline",
  "rose-outline",
  "happy-outline",
  "person-outline",
  "people-outline",
  "heart-circle-outline",
  "pulse-outline",
  "bandage-outline",
  "bed-outline",
  "shirt-outline",
  "watch-outline",
  "glasses-outline",
  "cut-outline",
  "cash-outline",
  "wallet-outline",
  "card-outline",
  "trending-up-outline",
  "stats-chart-outline",
  "calendar-outline",
  "time-outline",
  "alarm-outline",
  "timer-outline",
  "location-outline",
  "navigate-outline",
  "key-outline",
  "lock-closed-outline",
  "gift-outline",
  "balloon-outline",
  "rose-sharp",
  "infinite-outline",
];
